---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Lovesh Verma.
--- DateTime: 06-06-2021 01:02 PM
---

--POST REQUESTS TO SERVER (CALLBACKS)
ESX.RegisterServerCallback("mdt:server:saveEvidence", function(source, cb, data)
    local Player = ESX.GetPlayerFromId(source)
    local createdby = Player.identifier;
    oxmysql:execute("INSERT INTO `mdt_evidences` (`imgurl`, `description`, `type`, `date`, `createdby`) VALUES (@imgurl, @description, @type, @date, @createdby)", {
        ["@imgurl"] = EscapeSqli(data.imgurl),
        ["@description"] = EscapeSqli(data.description),
        ["@type"] = data.type,
        ["@date"] = EscapeSqli(data.date),
        ["@createdby"] = createdby
    }, function(result)
        local response = (result ~= nil)
        cb(response, result.insertId)
    end, true)
end)

function insertWarrants(data, incidentId, cb)
    for k,v in pairs(data.criminals) do
        if v.warrant.issue then
            oxmysql:execute("INSERT INTO `mdt_warrants` (`incident`, `date`, `identifier`) VALUES (@incident, @date, @identifier)", {
                ["@incident"] = incidentId,
                ["@date"] = v.warrant.date,
                ["@identifier"] = v.identifier
            }, function(result)
                local response = (result ~= nil)
                return cb(response)
            end, true)
        end
    end
    return cb(true)
end

ESX.RegisterServerCallback("mdt:server:saveIncident", function(source, cb, data)
    --New Incident
    if data.loadedIncident == 0 then
        local Player = ESX.GetPlayerFromId(source)
        local createdby = Player.identifier;
        oxmysql:execute("INSERT INTO `mdt_incidents` (`title`, `description`, `persons`, `officers`, `evidences`, `vehicles`, `criminals`, `date`, `createdby`) VALUES (@title, @description, @persons, @officers, @evidences, @vehicles, @criminals, @date, @createdby)", {
            ["@title"] = EscapeSqli(data.title),
            ["@description"] = EscapeSqli(data.description),
            ["@persons"] = json.encode(data.persons),
            ["@officers"] = json.encode(data.officers),
            ["@evidences"] = json.encode(data.evidences),
            ["@vehicles"] = json.encode(data.vehicles),
            ["@criminals"] = json.encode(data.criminals),
            ["@date"] = data.date,
            ["@createdby"] = createdby,
        }, function(insert)
            if insert == nil then return cb(false) end
            insertWarrants(data, insert.insertId, function (warrantResponse)
                cb(warrantResponse, insert.insertId)
            end)
        end, true)
    else --Edit Incident
        oxmysql:execute("UPDATE `mdt_incidents` SET `title` = @title, `description` = @description, `persons` = @persons, `officers` = @officers, `evidences` = @evidences, `vehicles` = @vehicles, `criminals` = @criminals WHERE `id` = @id", {
            ["@title"] = EscapeSqli(data.title),
            ["@description"] = EscapeSqli(data.description),
            ["@persons"] = json.encode(data.persons),
            ["@officers"] = json.encode(data.officers),
            ["@evidences"] = json.encode(data.evidences),
            ["@vehicles"] = json.encode(data.vehicles),
            ["@criminals"] = json.encode(data.criminals),
            ["@id"] = data.loadedIncident,
        }, function(update)
            if update == nil then return cb(false) end
            oxmysql:execute("DELETE FROM `mdt_warrants` WHERE `incident` = @incident", {
                ["@incident"] = data.loadedIncident,
            }, function(delete)
                if delete == nil then return cb(false) end
                insertWarrants(data, data.loadedIncident, function (warrantResponse)
                    cb(warrantResponse, data.loadedIncident)
                end)
            end, true)
        end, true)
    end
end)

ESX.RegisterServerCallback("mdt:server:SaveReport", function(source, cb, data)
    --New Report
    if data.loadedReport == 0 then
        local Player = ESX.GetPlayerFromId(source)
        local createdby = Player.identifier;
        oxmysql:execute("INSERT INTO `mdt_reports` (`type`, `title`, `description`, `persons`, `officers`, `evidences`, `vehicles`, `date`, `createdby`) VALUES (@type, @title, @description, @persons, @officers, @evidences, @vehicles, @date, @createdby )", {
            ["@type"] = EscapeSqli(data.type),
            ["@title"] = EscapeSqli(data.title),
            ["@description"] = EscapeSqli(data.description),
            ["@persons"] = json.encode(data.persons),
            ["@officers"] = json.encode(data.officers),
            ["@evidences"] = json.encode(data.evidences),
            ["@vehicles"] = json.encode(data.vehicles),
            ["@date"] = EscapeSqli(data.date),
            ["@createdby"] = createdby,
        }, function(insert)
            cb(insert ~= nil, insert.insertId)
        end, true)
    --Edit Report
    else
        oxmysql:execute("UPDATE `mdt_reports` SET `type` = @type, `title` = @title, `description` = @description, `persons` = @persons, `officers` = @officers, `evidences` = @evidences, `vehicles` = @vehicles WHERE `id` = @id", {
            ["@type"] = EscapeSqli(data.type),
            ["@title"] = EscapeSqli(data.title),
            ["@description"] = EscapeSqli(data.description),
            ["@persons"] = json.encode(data.persons),
            ["@officers"] = json.encode(data.officers),
            ["@evidences"] = json.encode(data.evidences),
            ["@vehicles"] = json.encode(data.vehicles),
            ["@id"] = data.loadedReport,
        }, function(update)
            cb(update ~= nil, data.loadedReport)
        end, true)
    end
end)

--Save Profiles
ESX.RegisterServerCallback("mdt:server:SaveVehicleProfile", function(source, cb, data)
    oxmysql:execute("INSERT INTO `mdt_vehicles` (plate, image, notes) VALUES(@plate, @image, @notes) ON DUPLICATE KEY UPDATE image=@image, notes=@notes", {
        ["@plate"] = data.plate,
        ["@image"] = EscapeSqli(data.image),
        ["@notes"] = EscapeSqli(data.notes),
    }, function(result)
        local response = result ~= nil and result.affectedRows > 0
        cb(response)
    end, true)
end)

ESX.RegisterServerCallback("mdt:server:SaveProfile", function(source, cb, data)
    oxmysql:execute("INSERT INTO `mdt_profiles` (identifier, image, notes) VALUES(@identifier, @image, @notes) ON DUPLICATE KEY UPDATE image=@image, notes=@notes", {
        ["@identifier"] = data.identifier,
        ["@image"] = EscapeSqli(data.image),
        ["@notes"] = EscapeSqli(data.notes),
    }, function(result)
        local response = result ~= nil and result.affectedRows > 0
        cb(response)
    end, true)
end)

ESX.RegisterServerCallback("mdt:server:SaveConfig", function(source, cb, data)
    local Player = ESX.GetPlayerFromId(source)
    local identifier = Player.identifier;
    oxmysql:execute("INSERT INTO `mdt_config` (identifier, sidebar, theme) VALUES (@identifier, @sidebar, @theme) ON DUPLICATE KEY UPDATE sidebar=@sidebar, theme=@theme", {
        ["@identifier"] = identifier,
        ["@sidebar"] = data.sidebar,
        ["@theme"] = data.theme,
    }, function(result)
        local response = result ~= nil
        cb(response)
    end, true)
end)

ESX.RegisterServerCallback("mdt:server:warrantAction", function(source, cb, data)
    oxmysql:execute("UPDATE `mdt_warrants` SET `approved` = @approved WHERE `id` = @id", {
        ["@approved"] = data.approved,
        ["@id"] = data.id,
    }, function(result)
        local response = (result ~= nil)
        cb(response)
    end, true)
end)


ESX.RegisterServerCallback("mdt:server:RemoveLicense", function(source, cb, identifier, id)
    print(id)
    print(identifier)

    oxmysql:execute("DELETE FROM `user_licenses` WHERE type = @type AND owner = @owner", {
        ["@owner"] = identifier,
        ["@type"] = id,
    }, function(delete)
        if delete == nil then return cb(false) end
        cb(true, id)
    end, true)
end)
