---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Lovesh Verma.
--- DateTime: 06-06-2021 10:55 AM
---

---Data Listings
ListData = {}
ListData.Query = {
    ["warrants"] = "SELECT mdt_warrants.id, mdt_warrants.incident, mdt_warrants.date, mdt_warrants.approved, mdt_incidents.title AS title, mdt_profiles.image, CONCAT (users.firstname,' ', users.lastname) AS name FROM mdt_warrants LEFT JOIN users ON mdt_warrants.identifier = users.identifier LEFT JOIN mdt_incidents ON mdt_warrants.incident = mdt_incidents.id LEFT JOIN mdt_profiles ON mdt_profiles.identifier = mdt_warrants.identifier WHERE CONCAT (users.firstname,' ', users.lastname) LIKE @search OR title LIKE @search OR mdt_warrants.incident = @search ORDER BY mdt_warrants.date DESC LIMIT 10",
    ["vehicles"] = "SELECT owned_vehicles.vehicle, owned_vehicles.plate, CONCAT (users.firstname,' ', users.lastname) AS owner FROM owned_vehicles INNER JOIN users ON owned_vehicles.owner = users.identifier WHERE owned_vehicles.plate LIKE @search LIMIT 10",
    ["profiles"] = "SELECT identifier, CONCAT(firstname,' ',lastname) AS name FROM users WHERE identifier LIKE @search OR  CONCAT (users.firstname,' ', users.lastname) LIKE @search LIMIT 10",
    ["incidents"] = "SELECT mdt_incidents.id, mdt_incidents.title, mdt_incidents.date, CONCAT (users.firstname,' ', users.lastname) AS createdbyname, mdt_incidents.createdby FROM mdt_incidents LEFT JOIN users ON mdt_incidents.createdby = users.identifier WHERE mdt_incidents.title LIKE @searchLike OR mdt_incidents.id = @search ORDER BY mdt_incidents.date DESC LIMIT 10",
    ["reports"] = "SELECT mdt_reports.type, mdt_reports.id, mdt_reports.title, mdt_reports.date, CONCAT (users.firstname,' ', users.lastname) AS createdbyname, mdt_reports.createdby FROM mdt_reports LEFT JOIN users ON mdt_reports.createdby = users.identifier WHERE mdt_reports.title LIKE @searchLike OR mdt_reports.id = @search ORDER BY mdt_reports.date DESC LIMIT 10",
    ["evidences"] = "SELECT mdt_evidences.id, mdt_evidences.description, mdt_evidences.type, mdt_evidences.date, mdt_evidences.createdby, CONCAT (users.firstname,' ', users.lastname) AS createdbyname FROM mdt_evidences LEFT JOIN users ON users.identifier = mdt_evidences.createdby WHERE mdt_evidences.description LIKE @searchLike OR mdt_evidences.id = @search ORDER BY mdt_evidences.date DESC LIMIT 10"
}
ListData.QueryParam = function (type, search)
    local escSearch = EscapeSqli(search)
    local searchLike = "%"..escSearch.."%"
    if type == "warrants" or type == "vehicles" or type == "profiles" then return { ["@search"] =  searchLike}
    else return {["@search"] = escSearch, ["@searchLike"] = searchLike} end

end

--Data Loadings
LoadData = {}
LoadData.Query = {
    ["incidents"] = "SELECT * FROM `mdt_incidents` WHERE id=@select LIMIT 1",
    ["reports"] = "SELECT * FROM `mdt_reports` WHERE id=@select LIMIT 1",
}
LoadData.QueryParam = function(id)
    return {["@select"] = id}
end
